# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a718850d8093b955eb38bbab7543eaa58c609896a6f63faa9221212b4db74ca969c2b43a5e432d168482c00323356a10cef22ead483322d44587118a0d19f332

test:
  secret_key_base: 9aa6bb4f1897086cfce1bbd6afd1bfc39314906ca195e576bc298b9c200f7f5c33f6d710a3fd9dedb3f8bbfc77cf7e0b3e444f4b68a8076ef931e85a000ceedc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
